services:
  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
      args:
        BUILDKIT_INLINE_CACHE: 0
    container_name: renclave-test-runner
    volumes:
      - ./target:/app/target
      - ./coverage:/app/coverage
      - ./performance-results:/app/performance-results
    environment:
      - RUST_LOG=info
      - CARGO_INCREMENTAL=0
    networks:
      - renclave-test
    command: [ "tail", "-f", "/dev/null" ] # Keep container running

  performance-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
      args:
        BUILDKIT_INLINE_CACHE: 0
    container_name: renclave-performance-runner
    volumes:
      - ./target:/app/target
      - ./coverage:/app/coverage
      - ./performance-results:/app/performance-results
    environment:
      - RUST_LOG=info
      - CARGO_INCREMENTAL=0
    networks:
      - renclave-test
    command: [ "tail", "-f", "/dev/null" ] # Keep container running

networks:
  renclave-test:
    driver: bridge

volumes:
  test-results:
  coverage:
