name: Generate Status Badges

# Generate and update CI/CD status badges in README
# Triggers on workflow completion to update badges

on:
  workflow_run:
    workflows: ["Renclave-v2 CI/CD", "Gauth CI/CD", "Web CI/CD"]
    types: [completed]
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run this workflow'
        required: false
        default: true
        type: boolean

jobs:
  update-badges:
    name: Update Status Badges
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    if: github.event.workflow_run.conclusion != 'skipped' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Generate Badge URLs
      run: |
        # Create a temporary file with the badges section
        cat > badges_section.md << 'EOF'
        
        ## CI/CD Status
        
        ### Component Workflows
        - **Renclave-v2**: ![Renclave-v2 CI/CD](https://github.com/${{ github.repository }}/actions/workflows/renclave-v2.yml/badge.svg)
        - **Gauth**: ![Gauth CI/CD](https://github.com/${{ github.repository }}/actions/workflows/gauth.yml/badge.svg)
        - **Web**: ![Web CI/CD](https://github.com/${{ github.repository }}/actions/workflows/web.yml/badge.svg)
        
        ### Badge Generation
        - **Status Badges**: ![Generate Status Badges](https://github.com/${{ github.repository }}/actions/workflows/badges.yml/badge.svg)
        
        *Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")*
        
        EOF
        
        # Check if badges section already exists in README
        if grep -q "## CI/CD Status" README.md; then
          # Find the line number of the first "## CI/CD Status" and the next "##" section (not ###)
          first_badge_line=$(grep -n "^## CI/CD Status" README.md | head -1 | cut -d: -f1)
          next_section_line=$(awk -v start="$first_badge_line" 'NR > start && /^##[^#]/ && !/^## CI\/CD Status/ { print NR; exit }' README.md)
          
          # If no next section found, use end of file
          if [ -z "$next_section_line" ]; then
            next_section_line=$(wc -l < README.md)
            next_section_line=$((next_section_line + 1))
          fi
          
          # Create new README: content before badges + new badges + content after badges
          head -n $((first_badge_line - 1)) README.md > README_new.md
          cat badges_section.md >> README_new.md
          tail -n +$next_section_line README.md >> README_new.md
          mv README_new.md README.md
        else
          # Add badges section after the first heading
          awk '
            NR == 1 { print; print ""; while ((getline line < "badges_section.md") > 0) print line; close("badges_section.md"); next }
            { print }
          ' README.md > README_new.md
          mv README_new.md README.md
        fi
        
        # Clean up temporary file
        rm badges_section.md
        
    - name: Commit Badge Updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update CI/CD status badges in README"
        git push
