name: Renclave-v2 CI/CD (DISABLED) (Improved)

# DISABLED: Only gauth.yml workflow is enabled
# This workflow is disabled to prevent conflicts with the main gauth workflow

on:
  # Disabled - will never trigger
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run all tests'
        required: false
        default: true
        type: boolean
      run_docker:
        description: 'Run Docker tests'
        required: false
        default: true
        type: boolean
      run_security:
        description: 'Run security scans'
        required: false
        default: true
        type: boolean
      rust_version:
        description: 'Rust version to use'
        required: false
        default: '1.82'
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.82"
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

jobs:
  # Quick checks that run first
  quick-checks:
    name: Quick Checks
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-quick-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    - name: Check code formatting
      run: |
        cd renclave-v2
        cargo fmt --all -- --check
        
    - name: Run clippy
      run: |
        cd renclave-v2
        cargo clippy --workspace -- -D warnings

  # Unit tests that run in parallel with quick checks
  unit-tests:
    name: Unit Tests
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-unit-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    - name: Run unit tests
      run: |
        cd renclave-v2
        # Run tests for each crate individually for better error reporting
        echo "Testing shared crate..."
        cargo test -p renclave-shared --verbose
        
        echo "Testing enclave crate..."
        cargo test -p renclave-enclave --verbose
        
        echo "Testing network crate..."
        cargo test -p renclave-network --verbose
        
        # Skip host crate tests as they may have dependency issues
        echo "Skipping host crate tests (dependency issues)"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results
        path: renclave-v2/target/test-results/
        retention-days: 3

  # Integration tests with better error handling
  integration-tests:
    name: Integration Tests
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [quick-checks, unit-tests]
    if: ${{ github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-integration-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker images
      run: |
        cd renclave-v2
        # Build with better error handling
        if ! docker compose -f docker/docker-compose.test.yml build; then
          echo "Docker build failed, checking logs..."
          docker compose -f docker/docker-compose.test.yml logs || true
          exit 1
        fi
        
    - name: Run integration tests
      run: |
        cd renclave-v2
        # Run integration tests with better error handling
        echo "Starting integration tests..."
        
        # Clean up any existing containers
        docker compose -f docker/docker-compose.test.yml down --volumes --remove-orphans || true
        
        # Start services
        if ! docker compose -f docker/docker-compose.test.yml up -d; then
          echo "Failed to start services, checking logs..."
          docker compose -f docker/docker-compose.test.yml logs || true
          exit 1
        fi
        
        # Wait for services to be ready
        echo "Waiting for services to be ready..."
        sleep 10
        
        # Check if services are running
        docker compose -f docker/docker-compose.test.yml ps
        
        # Run the actual tests
        if ! docker compose -f docker/docker-compose.test.yml run --rm test-runner /app/scripts/run-tests-docker.sh --integration; then
          echo "Integration tests failed, checking logs..."
          docker compose -f docker/docker-compose.test.yml logs || true
          exit 1
        fi
        
    - name: Collect test results
      if: always()
      run: |
        cd renclave-v2
        # Copy test results from container
        docker compose -f docker/docker-compose.test.yml cp renclave-test-runner:/app/test-results ./test-results/ || true
        docker compose -f docker/docker-compose.test.yml cp renclave-test-runner:/app/coverage ./coverage/ || true
        
    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: renclave-v2/test-results/
        retention-days: 3
        
    - name: Clean up Docker
      if: always()
      run: |
        cd renclave-v2
        docker compose -f docker/docker-compose.test.yml down --volumes --remove-orphans || true

  # E2E tests
  e2e-tests:
    name: E2E Tests
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [integration-tests]
    if: ${{ github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-e2e-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Run E2E tests
      run: |
        cd renclave-v2
        echo "Starting E2E tests..."
        
        # Clean up any existing containers
        docker compose -f docker/docker-compose.test.yml down --volumes --remove-orphans || true
        
        # Start services
        docker compose -f docker/docker-compose.test.yml up -d
        
        # Wait for services
        sleep 10
        
        # Run E2E tests
        if ! docker compose -f docker/docker-compose.test.yml run --rm test-runner /app/scripts/run-tests-docker.sh --e2e; then
          echo "E2E tests failed, checking logs..."
          docker compose -f docker/docker-compose.test.yml logs || true
          exit 1
        fi
        
    - name: Collect E2E test results
      if: always()
      run: |
        cd renclave-v2
        docker compose -f docker/docker-compose.test.yml cp renclave-test-runner:/app/test-results ./e2e-results/ || true
        
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: renclave-v2/e2e-results/
        retention-days: 3
        
    - name: Clean up Docker
      if: always()
      run: |
        cd renclave-v2
        docker compose -f docker/docker-compose.test.yml down --volumes --remove-orphans || true

  # Build and package
  build:
    name: Build Release
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [quick-checks, unit-tests]
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-build-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    - name: Build release
      run: |
        cd renclave-v2
        cargo build --release --workspace
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: renclave-v2-build
        path: renclave-v2/target/release/
        retention-days: 7

  # Security scanning
  security:
    name: Security Scan
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [quick-checks]
    if: ${{ github.event.inputs.run_security == 'true' || github.event_name != 'workflow_dispatch' }}
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-security-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    # cargo-audit is now pre-installed on the runner
        
    - name: Run security audit
      run: |
        cd renclave-v2
        cargo audit
        
    # cargo-deny is now pre-installed on the runner
        
    - name: Run cargo-deny
      run: |
        cd renclave-v2
        cargo deny check

  # Coverage reporting
  coverage:
    name: Coverage Report
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [unit-tests]
    if: ${{ github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: renclave-v2-coverage-${{ hashFiles('renclave-v2/Cargo.lock') }}
        target-dir: renclave-v2/target
        
    # cargo-tarpaulin is now pre-installed on the runner
        
    - name: Generate coverage report
      run: |
        cd renclave-v2
        mkdir -p coverage
        cargo tarpaulin --workspace --out Xml --output-dir coverage
        cargo tarpaulin --workspace --out Html --output-dir coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: renclave-v2/coverage/cobertura.xml
        flags: renclave-v2
        name: renclave-v2-coverage
        
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: renclave-v2/coverage/
        retention-days: 7

  # Summary job
  summary:
    name: Test Summary
    runs-on: [self-hosted, ovh, ubuntu-22.04]
    needs: [quick-checks, unit-tests, integration-tests, e2e-tests, build, security, coverage]
    if: always()
    
    steps:
    - name: Generate summary
      run: |
        echo "## Renclave-v2 Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Component Status:" >> $GITHUB_STEP_SUMMARY
        echo "- **Quick Checks**: ${{ needs.quick-checks.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Unit Tests**: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Integration Tests**: ${{ needs.integration-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **E2E Tests**: ${{ needs.e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build**: ${{ needs.build.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Security**: ${{ needs.security.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Coverage**: ${{ needs.coverage.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Determine overall status
        if [[ "${{ needs.quick-checks.result }}" == "success" && 
              "${{ needs.unit-tests.result }}" == "success" && 
              "${{ needs.build.result }}" == "success" ]]; then
          echo "✅ Core functionality passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Core functionality failed. Check individual job logs for details." >> $GITHUB_STEP_SUMMARY
        fi
        
        if [[ "${{ needs.integration-tests.result }}" == "success" && 
              "${{ needs.e2e-tests.result }}" == "success" ]]; then
          echo "✅ Integration tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️  Some integration tests failed or were skipped." >> $GITHUB_STEP_SUMMARY
        fi
